
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_AXI_GPIO_HEADER1_DEVICE_ID,
		XPAR_AXI_GPIO_HEADER1_BASEADDR,
		XPAR_AXI_GPIO_HEADER1_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_HEADER1_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_HEADER2_DEVICE_ID,
		XPAR_AXI_GPIO_HEADER2_BASEADDR,
		XPAR_AXI_GPIO_HEADER2_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_HEADER2_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_LEDS_DEVICE_ID,
		XPAR_AXI_GPIO_LEDS_BASEADDR,
		XPAR_AXI_GPIO_LEDS_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_LEDS_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_SWITCHES_DEVICE_ID,
		XPAR_AXI_GPIO_SWITCHES_BASEADDR,
		XPAR_AXI_GPIO_SWITCHES_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_SWITCHES_IS_DUAL
	}
};


