# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Spartan7S6MicroBlaze.xdc

# Block Designs: bd/MicroBlazeV2/MicroBlazeV2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeV2 || ORIG_REF_NAME==MicroBlazeV2} -quiet] -quiet

# IP: bd/MicroBlazeV2/ip/MicroBlazeV2_microblaze_0_0/MicroBlazeV2_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeV2_microblaze_0_0 || ORIG_REF_NAME==MicroBlazeV2_microblaze_0_0} -quiet] -quiet

# IP: bd/MicroBlazeV2/ip/MicroBlazeV2_dlmb_v10_0/MicroBlazeV2_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeV2_dlmb_v10_0 || ORIG_REF_NAME==MicroBlazeV2_dlmb_v10_0} -quiet] -quiet

# IP: bd/MicroBlazeV2/ip/MicroBlazeV2_ilmb_v10_0/MicroBlazeV2_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeV2_ilmb_v10_0 || ORIG_REF_NAME==MicroBlazeV2_ilmb_v10_0} -quiet] -quiet

# IP: bd/MicroBlazeV2/ip/MicroBlazeV2_dlmb_bram_if_cntlr_0/MicroBlazeV2_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeV2_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==MicroBlazeV2_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MicroBlazeV2/ip/MicroBlazeV2_ilmb_bram_if_cntlr_0/MicroBlazeV2_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeV2_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==MicroBlazeV2_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MicroBlazeV2/ip/MicroBlazeV2_lmb_bram_0/MicroBlazeV2_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeV2_lmb_bram_0 || ORIG_REF_NAME==MicroBlazeV2_lmb_bram_0} -quiet] -quiet

# IP: bd/MicroBlazeV2/ip/MicroBlazeV2_mdm_1_0/MicroBlazeV2_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeV2_mdm_1_0 || ORIG_REF_NAME==MicroBlazeV2_mdm_1_0} -quiet] -quiet

# IP: bd/MicroBlazeV2/ip/MicroBlazeV2_rst_clk_wiz_1_100M_0/MicroBlazeV2_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeV2_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==MicroBlazeV2_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/MicroBlazeV2/ip/MicroBlazeV2_axi_gpio_0_0/MicroBlazeV2_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeV2_axi_gpio_0_0 || ORIG_REF_NAME==MicroBlazeV2_axi_gpio_0_0} -quiet] -quiet

# IP: bd/MicroBlazeV2/ip/MicroBlazeV2_xbar_0/MicroBlazeV2_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeV2_xbar_0 || ORIG_REF_NAME==MicroBlazeV2_xbar_0} -quiet] -quiet

# IP: bd/MicroBlazeV2/ip/MicroBlazeV2_microblaze_0_axi_periph_0/MicroBlazeV2_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeV2_microblaze_0_axi_periph_0 || ORIG_REF_NAME==MicroBlazeV2_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/MicroBlazeV2/ip/MicroBlazeV2_axi_uartlite_0_0/MicroBlazeV2_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeV2_axi_uartlite_0_0 || ORIG_REF_NAME==MicroBlazeV2_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/MicroBlazeV2/ip/MicroBlazeV2_axi_gpio_1_0/MicroBlazeV2_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeV2_axi_gpio_1_0 || ORIG_REF_NAME==MicroBlazeV2_axi_gpio_1_0} -quiet] -quiet

# IP: bd/MicroBlazeV2/ip/MicroBlazeV2_axi_gpio_0_1/MicroBlazeV2_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeV2_axi_gpio_0_1 || ORIG_REF_NAME==MicroBlazeV2_axi_gpio_0_1} -quiet] -quiet

# IP: bd/MicroBlazeV2/ip/MicroBlazeV2_axi_gpio_1_1/MicroBlazeV2_axi_gpio_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeV2_axi_gpio_1_1 || ORIG_REF_NAME==MicroBlazeV2_axi_gpio_1_1} -quiet] -quiet

# XDC: c:/Users/louis/Documents/Github/PCB ADVANCED/PCB-ADVANCED/VIVADO/SpartanMicroBlaze/SpartanMicroBlaze.gen/sources_1/bd/MicroBlazeV2/MicroBlazeV2_ooc.xdc
