# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/louis/Documents/Github/PCB ADVANCED/PCB-ADVANCED/VIVADO/SpartanMicroBlaze/SpartanMicroBlaze.srcs/sources_1/bd/MicroBlazeV2/ip/MicroBlazeV2_rst_clk_wiz_1_100M_0/MicroBlazeV2_rst_clk_wiz_1_100M_0.xci
# IP: The module: 'MicroBlazeV2_rst_clk_wiz_1_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/louis/Documents/Github/PCB ADVANCED/PCB-ADVANCED/VIVADO/SpartanMicroBlaze/SpartanMicroBlaze.gen/sources_1/bd/MicroBlazeV2/ip/MicroBlazeV2_rst_clk_wiz_1_100M_0/MicroBlazeV2_rst_clk_wiz_1_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlazeV2_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/louis/Documents/Github/PCB ADVANCED/PCB-ADVANCED/VIVADO/SpartanMicroBlaze/SpartanMicroBlaze.gen/sources_1/bd/MicroBlazeV2/ip/MicroBlazeV2_rst_clk_wiz_1_100M_0/MicroBlazeV2_rst_clk_wiz_1_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlazeV2_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/louis/Documents/Github/PCB ADVANCED/PCB-ADVANCED/VIVADO/SpartanMicroBlaze/SpartanMicroBlaze.gen/sources_1/bd/MicroBlazeV2/ip/MicroBlazeV2_rst_clk_wiz_1_100M_0/MicroBlazeV2_rst_clk_wiz_1_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlazeV2_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/louis/Documents/Github/PCB ADVANCED/PCB-ADVANCED/VIVADO/SpartanMicroBlaze/SpartanMicroBlaze.srcs/sources_1/bd/MicroBlazeV2/ip/MicroBlazeV2_rst_clk_wiz_1_100M_0/MicroBlazeV2_rst_clk_wiz_1_100M_0.xci
# IP: The module: 'MicroBlazeV2_rst_clk_wiz_1_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/louis/Documents/Github/PCB ADVANCED/PCB-ADVANCED/VIVADO/SpartanMicroBlaze/SpartanMicroBlaze.gen/sources_1/bd/MicroBlazeV2/ip/MicroBlazeV2_rst_clk_wiz_1_100M_0/MicroBlazeV2_rst_clk_wiz_1_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlazeV2_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/louis/Documents/Github/PCB ADVANCED/PCB-ADVANCED/VIVADO/SpartanMicroBlaze/SpartanMicroBlaze.gen/sources_1/bd/MicroBlazeV2/ip/MicroBlazeV2_rst_clk_wiz_1_100M_0/MicroBlazeV2_rst_clk_wiz_1_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlazeV2_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/louis/Documents/Github/PCB ADVANCED/PCB-ADVANCED/VIVADO/SpartanMicroBlaze/SpartanMicroBlaze.gen/sources_1/bd/MicroBlazeV2/ip/MicroBlazeV2_rst_clk_wiz_1_100M_0/MicroBlazeV2_rst_clk_wiz_1_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlazeV2_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
